### PR TITLE
Update JSON files with device tree information

### PR DESCRIPTION
**Pull request by RekhaAparna01**
This commit adds JSON files and updates these JSON files with the device tree information of the respective system type and install JSON files via meson.

Change-Id: Ie1af5b3de572cb10aec56a4923ed6c48075192f6
Signed-off-by: RekhaAparna01 <vrekhaaparna@ibm.com>

### CODE REVIEW

**Comment by RekhaAparna01** [comment]
jenkins run tests please

**Review by SunnySrivastava1984 — APPROVED** [review]

**Review by jinuthomas — CHANGES_REQUESTED** [review]
I would expect a base file only and not a copy paste for P-future

**Comment by PriyangaRamasamy** [comment]
> I would expect a base file only and not a copy paste for P-future

Am concerned on the same, and I would expect only device tree change as part of this PR

**Comment by SunnySrivastava1984** [comment]
> > I would expect a base file only and not a copy paste for P-future
> 
> Am concerned on the same, and I would expect only device tree change as part of this PR

There is no JSONs for P11/future as of now. To have only device tree we will need to have base JSONs. Now since there is no workbook available now. JSONs has been copy pasted from 1060.

**Comment by PriyangaRamasamy** [comment]
> There is no JSONs for P11/future as of now. To have only device tree we will need to have base JSONs. Now since there is no workbook available now. JSONs has been copy pasted from 1060.

why do we need to pull P10 systems json into P11 branch? Is it just for testing?

**Comment by SunnySrivastava1984** [comment]
> > There is no JSONs for P11/future as of now. To have only device tree we will need to have base JSONs. Now since there is no workbook available now. JSONs has been copy pasted from 1060.
> 
> why do we need to pull P10 systems json into P11 branch? Is it just for testing?

yes, since most of the helper codes will be ported. We need to ensure everything moved correctly.

**Comment by PriyangaRamasamy** [comment]
As @SunnySrivastava1984 said, instead of restricting the testing on one of the machines, I suggest, we can update all jsons with device-tree information.
why can't we split this into two commits - one has the base json from p10 and another has just the device tree info (req for p11).

**Review by SunnySrivastava1984 — CHANGES_REQUESTED** [review]
Pull the base vpd_inventory.JSON as well as it is in 1060, so that we can test the "selection of JSON on boot" functionality.

**Review by SunnySrivastava1984 — APPROVED** [review]

**Review by jinuthomas — APPROVED** [review]

**Pull request merged**
