### PR TITLE
Allow byte array values in extraInterfaces

### PR DESCRIPTION
**Pull request by santoshpuranik**
Upstream commit is here: https://gerrit.openbmc-project.xyz/c/openbmc/openpower-vpd-parser/+/45849

### CODE REVIEW

**Review by jinuthomas — APPROVED** [review]
looks good to me

**Comment by santoshpuranik** [comment]
The upstream commit is merged. @rfrandse : Could you please do a master rebase?

**Comment by geissonator** [comment]
add to approvelist

**Comment by santoshpuranik** [comment]
This is merged upstream.

**Pull request closed without merging**
