### PR TITLE
Update generic parser implementation

### PR DESCRIPTION
**Pull request by SunnySrivastava1984**
Updating the implementation of generic parser to make use of worker class.

User can pass a config file in case of generic parser as well and that will require special handling of flags mentioned in the config JSON in the process of parsing the data.

User can also make use of "Parser" class directly to skip all the sepcial handling of flags.

### CODE REVIEW

**Comment by SunnySrivastava1984** [comment]
jenkins -> run tests please

**Comment by SunnySrivastava1984** [comment]
jenkin -> run tests please

**Comment by geissonator** [comment]
Got CI running again, please take a look:
```
[14/29] Compiling C++ object vpd-parser.p/src_parser.cpp.o
FAILED: vpd-parser.p/src_parser.cpp.o 
c++ -Ivpd-parser.p -I. -I.. -I../include -I../configuration -I/usr/local/include -fdiagnostics-color=never -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c++20 -Og -g -Wno-psabi -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -MD -MQ vpd-parser.p/src_parser.cpp.o -MF vpd-parser.p/src_parser.cpp.o.d -o vpd-parser.p/src_parser.cpp.o -c ../src/parser.cpp
In file included from ../src/parser.cpp:3:
../include/utils.hpp: In function ‘std::vector<std::__cxx11::basic_string<char> > vpd::utils::executeCmd(T&&, Types ...)’:
../include/utils.hpp:152:44: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
  152 |     std::unique_ptr<FILE, decltype(&pclose)> cmdPipe(popen(cmd.c_str(), "r"),
      |                                            ^
cc1plus: all warnings being treated as errors
```
https://sys-openbmc-dev-jenkins.swg-devops.com/job/OpenBMC-Dev/job/build/job/github-public/job/repo-ci/job/public-ibm-openbmc-downstream-repo-ci-pr-openpower-vpd-parser/278/console

**Comment by SunnySrivastava1984** [comment]
jenkins -> run tests please

**Pull request merged**
