### PR TITLE
P11 JSON:Refactored everest system JSON.

### PR DESCRIPTION
**Pull request by PriyangaRamasamy**
P11 JSON:Refactored everest system JSON
This commit has everest system JSON refactored with the following
modifications.

1. Added devTree tag.
2. Added backupRestoreConfigPath tag.
3. Added serviceName in every parent FRU and sub FRU section.
4. Modified preAction and PostFailAction sections as per P11 code.
5. Removed busType, driverType and devAddress as we have systemCmd tag
which has command to bind.
6. Updated inventoryPath tag with complete path.
7. Removed pcaChipAddress tag as we hardcode it's bind command in
postAction section.
8. Added postAction section wherever required.

### CODE REVIEW

**Review by SunnySrivastava1984 — APPROVED** [review]
Looks good to me.

**Comment by PriyangaRamasamy** [comment]
resolved clang-formatting issues in the latest patchset

**Review by jinuthomas — CHANGES_REQUESTED** [review]
Please recheck the PCIe lines , have not gone to the DIMMs yet

**Comment by PriyangaRamasamy** [comment]
> Please recheck the PCIe lines , have not gone to the DIMMs yet

looks good to me

**Comment by PriyangaRamasamy** [comment]
I have updated presence pin info for tpm, dasd bp, lcd panel, base panel, fan and dcm. Please have a look.
vrm gpio presence pin info is not found in device tree. once it is added in device tree will update the json.

**Review by jinuthomas — APPROVED** [review]
Looks good

**Pull request merged**
